"""add_extra_audit_fields

Revision ID: bd0b0256642a
Revises: e395415d7fcb
Create Date: 2026-03-20 13:17:11.231549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0b0256642a'
down_revision: Union[str, None] = 'e395415d7fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('method', sa.String(length=10), nullable=True))
    op.add_column('audit_logs', sa.Column('path', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('response_body', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'response_body')
    op.drop_column('audit_logs', 'path')
    op.drop_column('audit_logs', 'method')
    # ### end Alembic commands ###
