"""Add otp_verifications table and update user columns

Revision ID: f33fee3d99dc
Revises: bd0b0256642a
Create Date: 2026-03-20 16:03:27.593768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33fee3d99dc'
down_revision: Union[str, None] = 'bd0b0256642a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('otp_type', sa.String(length=20), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier', 'otp_type', name='uq_otp_identifier_type')
    )
    op.create_index(op.f('ix_otp_verifications_identifier'), 'otp_verifications', ['identifier'], unique=False)
    op.create_index(op.f('ix_otp_verifications_otp_type'), 'otp_verifications', ['otp_type'], unique=False)
    op.add_column('user_login', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('user_login', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_login', 'is_verified')
    op.drop_column('user_login', 'name')
    op.drop_index(op.f('ix_otp_verifications_otp_type'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_identifier'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    # ### end Alembic commands ###
